### ISSUE TITLE
Paging kannski?

### ISSUE THREAD

**Issue by tomaskri** [nikhil7e/ReitHI-android#10]
Það þarf þá að tala um hvernig við viljum útfæra það því ef við sendum t.d. request á gagnagrunninn um að fá bara 10 results og síðan erum við að filtera áður en að við birtum þá birtast kannski bara 2 course en ættu að vera mögulega 10+

**Comment by nikhil7e** [comment]
Basic previous-next paging komið. Mögulega bæta við einhverju meira fancy.
